# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

matrix:
  0.9.0:
    vllm: "0.14.1"
    sglang: "0.5.8"
    trtllm: "1.3.0rc1"
  0.8.1.post1:
    vllm: "0.12.0"
    sglang: "0.5.6.post2"
    trtllm: "1.2.0rc6.post1"
  0.8.1:
    vllm: "0.12.0"
    sglang: "0.5.6.post2"
    trtllm: "1.2.0rc6.post1"
  0.8.0:
    vllm: "0.12.0"
    sglang: "0.5.6.post2"
    trtllm: "1.2.0rc6.post1"
  0.7.1:
    vllm: "0.11.0"
    sglang: "0.5.4.post3"
    trtllm: "1.2.0rc3"
  0.7.0.post1:
    vllm: "0.11.0"
    sglang: "0.5.4.post3"
    trtllm: "1.2.0rc3"
  0.7.0:
    vllm: "0.11.0"
    sglang: "0.5.4.post3"
    trtllm: "1.2.0rc2"
  0.6.1.post1:
    vllm: "0.11.0"
    sglang: "0.5.3.post2"
    trtllm: "1.1.0rc5"
  0.6.1:
    vllm: "0.11.0"
    sglang: "0.5.3.post2"
    trtllm: "1.1.0rc5"
  0.6.0:
    vllm: "0.11.0"
    sglang: "0.5.3.post2"
    trtllm: "1.1.0rc5"
